spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      suffix: .html
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://h2o.cfyalaxuh5ve.ap-northeast-2.rds.amazonaws.com/h2o
    username: h2o
    password: wjdqhqhdks!